<a href="https://colab.research.google.com/github/Jin-jin-jara/misc/blob/master/tf_function_annotation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%tensorflow_version 2.x
import tensorflow as tf

TensorFlow 2.x selected.


tf.function : tf.function의 새로운 특징은 오토그래프 (AutoGraph)입니다. tf.function을 함수에 붙여줄 경우, 여전히 다른 일반 함수들처럼 사용할 수 있습니다. 하지만 그래프 내에서 컴파일 되었을 때는 더 빠르게 실행하고, GPU나 TPU를 사용해서 작동하고, 세이브드모델(SavedModel)로 내보내는 것이 가능해집니다.

In [3]:
@tf.function
def f(x, y):
  return x**2 + y

x = tf.constant([2,3])   # <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>
y = tf.constant([3, -2])   # <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 3, -2], dtype=int32)>

# 작동 방식은 일반 함수와 똑같다!

f(x, y)  # <tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 7], dtype=int32)>

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 7], dtype=int32)>

In [4]:
@tf.function
def square_if_positive(x):
  if x > 0:
    x = x * x
  else:
    x = 0
  return x


print('square_if_positive(2) = {}'.format(square_if_positive(tf.constant(2))))
print('square_if_positive(-2) = {}'.format(square_if_positive(tf.constant(-2))))

square_if_positive(2) = 4
square_if_positive(-2) = 0


In [5]:
@tf.function
def return_square(x):
  if x[0] > 0:
    return x**2
  else:
    return x

return_square(tf.constant([2, -2]))

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 4], dtype=int32)>

In [6]:
def return_square(x):
  if x[0] > 0:
    return x**2
  else:
    return x

return_square(tf.constant([2, -2]))

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 4], dtype=int32)>